# Generated by Django 5.0 on 2023-12-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tasks_delete_taks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
