# Generated by Django 5.0 on 2023-12-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_task_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='task_tb',
        ),
    ]
